Vector
klinachev/first-term pull request #1
Opened 2020-06-21 11:33 UTC by klinachev

2020-06-22 01:50 UTC, kt-cpp requested changes
Проверил, но при переписывании с учетом исключений и утечек памяти код может сильно поменяться, поэтому не слишком глубоко смотрел

2020-06-22 01:50 UTC, kt-cpp commented on vector/vector.h
> +    vector& newCapacityCopy(size_t, vector const&);
Следуй общему ```case```

2020-06-22 01:50 UTC, kt-cpp commented on vector/vector.h
> +    return static_cast<T*>(static_cast<T*>(operator new(size * sizeof(T))));
Зачем еще один ```cast```?

2020-06-22 01:50 UTC, kt-cpp commented on vector/vector.h
> +}
В таком конструкторе я ожидаю, что поля дефолтно проинициализируются. И этот конструктор не нужен в данном случае (в тестах). Давай его выпилим.

2020-06-22 01:50 UTC, kt-cpp commented on vector/vector.h
> +}
Касты здесь, конечно излишни, но ладно

Тем не менее сбивает с толку, что ты кастишь к ```iterator```, а возвращаешь, например, ```const_iterator```

2020-06-22 01:50 UTC, kt-cpp commented on vector/vector.h
> +    assert(size_ > first - begin() && first >= begin() && size_ > first - begin() && first >= begin());
Перемудрил, в последних двух сравнениях должен быть ```last```

2020-06-22 01:50 UTC, kt-cpp commented on vector/vector.h
> +    assert(size_ > first - begin() && first >= begin() && size_ > first - begin() && first >= begin());
И везде так

\+ к этому, можно тогда и поассертить, что ```last > first```

2020-06-22 01:50 UTC, kt-cpp commented on vector/vector.h
> +}
```erase(pos, pos + 1)```

2020-06-22 01:50 UTC, kt-cpp commented on vector/vector.h
> +}
3 копирования вместо одного, это плохо.

2020-06-22 01:50 UTC, kt-cpp commented on vector/vector.h
> +}
Эти вызовы ```newCapacityCopy``` выглядят ужасно

2020-06-22 01:50 UTC, kt-cpp commented on vector/vector.h
> +        data_[--size_].~T();
```pop_back```

2020-06-22 01:50 UTC, kt-cpp commented on vector/vector.h
> +    }
```clear```

2020-06-22 01:50 UTC, kt-cpp commented on vector/vector.h
> +}
Вам нужно думать об утечках памяти и исключениях, но нигде не вижу ```try-catch``` блока. Переписать.

2020-06-22 01:57 UTC, kt-cpp requested changes
Добавил тест, раз автотесты прошли

2020-06-22 01:57 UTC, kt-cpp commented on vector/vector.h
> +}
```
TEST(correctness, copy_throw) {
  vector<element<size_t> > a;
  a.reserve(10);
  size_t n = a.capacity();
  for (size_t i = 0; i != n; ++i) a.push_back(i);
  element<size_t>::set_throw_countdown(7);
  EXPECT_THROW({
      vector<element<size_t>> b(a);
  }, std::runtime_error);
}
```
Память течет на таком тесте

2020-06-22 11:31 UTC, klinachev commented on vector/vector.h
> +    return static_cast<T*>(static_cast<T*>(operator new(size * sizeof(T))));
убрал

2020-06-22 11:32 UTC, klinachev commented on vector/vector.h
> +}
удалил конструктор

2020-06-22 11:32 UTC, klinachev commented on vector/vector.h
> +}
убрал касты

2020-06-22 11:33 UTC, klinachev commented on vector/vector.h
> +    assert(size_ > first - begin() && first >= begin() && size_ > first - begin() && first >= begin());
исправил

2020-06-22 11:36 UTC, klinachev commented on vector/vector.h
> +}
заменил на `erase(pos, pos + 1)`

2020-06-22 11:37 UTC, klinachev commented on vector/vector.h
> +        data_[--size_].~T();
исправил

2020-06-22 11:37 UTC, klinachev commented on vector/vector.h
> +    }
исправил

2020-06-22 11:38 UTC, klinachev commented on vector/vector.h
> +}
изменил

2020-06-22 11:47 UTC, klinachev commented on vector/vector.h
> +    vector& newCapacityCopy(size_t, vector const&);
`push_back_realloc' нужен только в `push_back`, а для остальных методов у меня аналогичные и в изначальном задании этих методов не было

2020-06-22 11:48 UTC, klinachev commented on vector/vector.h
> +}
изменил

2020-06-22 11:54 UTC, klinachev commented on vector/vector.h
> +}
Память утекала из-за неправильного конструктора копирования, как я понял.
Я пытаюсь избежать утечек памяти за счет swap trick.
`newCapacityCopy` изменил.

2020-06-22 13:10 UTC, kt-cpp commented on vector/vector.h
> +    vector& newCapacityCopy(size_t, vector const&);
Ты не понял :)

Я про ```camelCase``` vs ```snake_case```

Это конечно вкусовщина - но по-хорошему всегда нужно выбирать один из двух

2020-06-22 14:29 UTC, kt-cpp commented on vector/vector.h
> +}
Со свапом есть свои тонкости, но пойдет

2020-06-22 14:51 UTC, kt-cpp requested changes
Все норм, осталось чуть-чуть дофиксить

2020-06-22 14:51 UTC, kt-cpp commented on vector/vector.h
> +}
Здесь не ```strong``` гарантии, но легко фиксится

2020-06-22 14:51 UTC, kt-cpp commented on vector/vector.h
> +}
По желанию можно сделать эту фукнцию статической

2020-06-22 23:16 UTC, klinachev commented on vector/vector.h
> +    vector& newCapacityCopy(size_t, vector const&);
Переименовал

2020-06-22 23:18 UTC, klinachev commented on vector/vector.h
> +}
Убрал возвращаемое значение, оно нигде не использовалось

2020-06-23 07:58 UTC, klinachev commented on vector/vector.h
> +}
Пофиксил

2020-06-23 08:51 UTC, merged