Bigint
klinachev/first-term pull request #2
Opened 2020-06-26 21:31 UTC by klinachev

2020-06-27 17:54 UTC, klinachev commented
Переделал с вектором

2020-07-01 15:04 UTC, kt-cpp requested changes

2020-07-01 15:04 UTC, kt-cpp commented on bigint/big_integer.h
> +    big_integer& operator*=(big_integer);
Почему здесь передается не по константной ссылке?

2020-07-01 15:04 UTC, kt-cpp commented on bigint/big_integer.h
> +    big_integer const operator++(int);
Здесь не нужен `const`. Аналогично в `big_integer const operator--(int)`

2020-07-01 15:04 UTC, kt-cpp commented on bigint/big_integer.cpp
> +uint32_t *big_integer::non_const_data() const {
> Modifying a const object through a non-const access path <...> results in undefined behavior.

Вообще, если в функцию передан const-объект, это более-менее явно намекает на то, что изменять его нельзя.

2020-07-01 15:04 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    buf[0] = *reinterpret_cast<uint32_t*>(&a);
Чем этот вариант лучше `static_cast<uint32_t>(a)`?

2020-07-01 15:04 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    int len = str.length(), start = 0;
`size_t`

2020-07-01 15:04 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if (a.buf.size()== b.buf.size()) {
здесь и в остальных подобных местах поправь код-стайл, пожалуйста

2020-07-01 15:04 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if ((buf.size()< rhs.buf.size() && this_sign) || (buf.size() > rhs.buf.size() && rhs_sign))
поставь, пожалуйста, фигурные скобки после ифов — так гораздо удобнее будет читать

2020-07-01 15:04 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    std::vector<uint32_t> mas(std::max(rhs.buf.size(), buf.size()) + 1);
[minor] mas — massiv?

2020-07-01 15:04 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    uint32_t toAdd = 0, i = 0;
Желательно придерживаться одной и той же конвенции по именованию — либо camelCase, либо snake_case.

2020-07-01 15:04 UTC, kt-cpp commented on bigint/big_integer.cpp
> +void big_integer::divide(big_integer x, big_integer y, big_integer &d, big_integer &r) {
[note] Почему бы не возвращать пару из этой и подобных функций? Везде, где ты используешь эти функции, можно попробовать применить structural bindings из C++17.

2020-07-01 15:04 UTC, kt-cpp commented on bigint/big_integer.cpp
> +uint32_t big_integer::small_div(uint32_t divisor) {
[minor] Из названия функции совершенно не очевидно, что она делает. Возможно, стоит переименовать или хотя бы оставить комментарий.

2020-07-01 15:04 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    if (this_sign) a = -*this;
Тут ты копируешь оба операнда, достаточно копировать один из них.

2020-07-01 15:04 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    d.non_const_data()[d.buf.size() - 1] = 0;
Странно, что где-то ты пишешь в non_const_data, а где-то — создаешь отдельный вектор, пишешь туда, потом а делаешь change_data.

Почему бы везде не писать в non_const_data, и делать clear_empty_slots?

2020-07-01 15:04 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    uint32_t n, m = y.buf.size(), xs;
используй `size_t` для размеров буферов, индексов и т.п.

2020-07-01 15:04 UTC, kt-cpp commented on bigint/big_integer.cpp
> +uint32_t big_integer::trial(big_integer const&r, big_integer const&d, uint32_t m, uint32_t k) {
[style] названия функций и переменных не отражают их назначение

2020-07-03 22:30 UTC, klinachev commented on bigint/big_integer.h
> +    big_integer& operator*=(big_integer);
Исправил

2020-07-03 22:30 UTC, klinachev commented on bigint/big_integer.h
> +    big_integer const operator++(int);
Убрал

2020-07-03 22:30 UTC, klinachev commented on bigint/big_integer.cpp
> +uint32_t *big_integer::non_const_data() const {
Убрал `const`

2020-07-03 22:31 UTC, klinachev commented on bigint/big_integer.cpp
> +    int len = str.length(), start = 0;
Заменил

2020-07-03 22:31 UTC, klinachev commented on bigint/big_integer.cpp
> +    if (a.buf.size()== b.buf.size()) {
Поправил

2020-07-03 22:31 UTC, klinachev commented on bigint/big_integer.cpp
> +    if ((buf.size()< rhs.buf.size() && this_sign) || (buf.size() > rhs.buf.size() && rhs_sign))
Поставил

2020-07-03 22:31 UTC, klinachev commented on bigint/big_integer.cpp
> +    std::vector<uint32_t> mas(std::max(rhs.buf.size(), buf.size()) + 1);
Переименовал в `vector`

2020-07-03 22:32 UTC, klinachev commented on bigint/big_integer.cpp
> +    uint32_t toAdd = 0, i = 0;
Поменял

2020-07-03 22:33 UTC, klinachev commented on bigint/big_integer.cpp
> +uint32_t big_integer::small_div(uint32_t divisor) {
Переименовал в `div_by_uint32_t`

2020-07-03 22:33 UTC, klinachev commented on bigint/big_integer.cpp
> +    if (this_sign) a = -*this;
Изменил

2020-07-03 22:33 UTC, klinachev commented on bigint/big_integer.cpp
> +    uint32_t n, m = y.buf.size(), xs;
Заменил

2020-07-03 22:35 UTC, klinachev commented on bigint/big_integer.cpp
> +uint32_t big_integer::trial(big_integer const&r, big_integer const&d, uint32_t m, uint32_t k) {
Переименовал в `get_trial_multiplier`

2020-07-03 22:43 UTC, klinachev commented on bigint/big_integer.cpp
> +    d.non_const_data()[d.buf.size() - 1] = 0;
`change_data` и соответственно `clear_empty_slots` может бросить исключение и тогда содержимое бигинта должно остаться прежним. `non_const_data` я использую только для тех бигинтов, которые используются в промежуточных вычислениях.

2020-07-03 23:56 UTC, klinachev commented on bigint/big_integer.cpp
> +    buf[0] = *reinterpret_cast<uint32_t*>(&a);
Если `a` отрицательное то `static_cast<uint32_t>(a)` это ub. И вроде в чатике тг Лев сказал что у такого каста больше гарантий.

2020-07-04 00:31 UTC, klinachev commented on bigint/big_integer.cpp
> +void big_integer::divide(big_integer x, big_integer y, big_integer &d, big_integer &r) {
Не стал менять

2020-07-04 23:12 UTC, kt-cpp requested changes
Почти ок

2020-07-04 23:12 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    uint32_t bigShift = rhs / 32u, shift = rhs % 32u;
[style] Остались маленькие проблемы со названиями переменных

2020-07-04 23:13 UTC, kt-cpp commented
И, пожалуйста, разберись с гитом — сейчас смёрджить нельзя из-за конфликтов.

2020-07-05 12:50 UTC, klinachev commented on bigint/big_integer.cpp
> +    uint32_t bigShift = rhs / 32u, shift = rhs % 32u;
Изменил.

2020-07-06 17:30 UTC, kt-cpp approved these changes

2020-07-06 17:30 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        buf.resize(2);
[note] buf = {a, 0}

2020-07-06 17:30 UTC, merged