Add asm
klinachev/first-term pull request #4
Opened 2020-06-28 11:30 UTC by klinachev

2020-06-28 23:23 UTC, kt-cpp commented on asm/mul.asm
> +                mov             rcx, 128
Кажется ```rcx``` и так равен 128 уже

2020-06-28 23:26 UTC, kt-cpp commented on asm/mul.asm
> +                mov             rcx, 256 * 3 + 8
```mov rcx, 3 * 128 * 2 + 8``` смотрелось бы лучше

2020-06-28 23:27 UTC, kt-cpp commented on asm/mul.asm
> +                mov             rcx, 129
```inc rcx```

2020-06-28 23:27 UTC, kt-cpp commented on asm/mul.asm
> +                mov             rax, 0
```xor rax, rax```

2020-06-28 23:29 UTC, kt-cpp commented on asm/mul.asm
> +                mov             r8, 128
Почему нельзя запушить здесь регистр, в котором у тебя есть уже 128, а потом сделать pop

Хотя это вкусовщина, как хочешь

2020-06-28 23:30 UTC, kt-cpp commented on asm/mul.asm
> +                lea             rdi, [rdi + 3 * 128 * 8 + 8]
Собственно, нет смысла сохранять значение ```rdi```

2020-06-28 23:31 UTC, kt-cpp commented on asm/mul.asm
> +                jnz             .copy
А давай выделим в функцию всё же, должно получиться лучше

2020-06-28 23:33 UTC, kt-cpp commented on asm/mul.asm
> +                lea             rsi, [r10 + 8]
Как-то странно, что ```rsi = r10 + 8```, кажется можно сделать так что бы все-таки ```rsi += 8```, чтобы стало прозрачнее

2020-06-28 23:34 UTC, kt-cpp commented on asm/mul.asm
> +                lea             rdi, [r10 + 2 * 128 * 8 + 8]
Мне не нравится что ты постоянно высчитываешь 2 * 128 * 8 и добавляешь к изначальным смещениям

Может выделить что-то в регистр и сохранить в самом начале?

2020-06-28 23:36 UTC, kt-cpp commented on asm/mul.asm
> +                sub             rsp, 5 * 128 * 8 + 8
А давай попортим стэк в ```mul_long_long```

Т.е. здесь выдели 4 * 128 * 8 = 2 * 128 * 8(ответ) + 128 * 8(операнд) + 128 * 8(операнд)

А в функции умножения 129 * 8 для грязных вычислений

2020-06-28 23:38 UTC, kt-cpp requested changes
Вроде все рабочее и даже оптимально по памяти для такого алгоритма, поэтому в целом все хорошо

Но код сложно читать и над этим надо поработать

2020-06-29 01:03 UTC, klinachev commented on asm/mul.asm
> +                mov             rcx, 128
Убрал

2020-06-29 01:06 UTC, klinachev commented on asm/mul.asm
> +                mov             rcx, 256 * 3 + 8
Убрал из функции константы 128 и 256, теперь функция работает для любого `rcx`.

2020-06-29 01:07 UTC, klinachev commented on asm/mul.asm
> +                mov             rax, 0
Заменил

2020-06-29 01:07 UTC, klinachev commented on asm/mul.asm
> +                mov             r8, 128
Изменил

2020-06-29 01:08 UTC, klinachev commented on asm/mul.asm
> +                lea             rdi, [rdi + 3 * 128 * 8 + 8]
Убрал

2020-06-29 01:08 UTC, klinachev commented on asm/mul.asm
> +                jnz             .copy
Сделал функцию `copy_long`

2020-06-29 01:08 UTC, klinachev commented on asm/mul.asm
> +                lea             rsi, [r10 + 8]
Изменил

2020-06-29 01:09 UTC, klinachev commented on asm/mul.asm
> +                lea             rdi, [r10 + 2 * 128 * 8 + 8]
Выделил регистр `r9`, для этого.

2020-06-29 01:10 UTC, klinachev commented on asm/mul.asm
> +                sub             rsp, 5 * 128 * 8 + 8
Сделал

2020-06-29 01:27 UTC, kt-cpp commented on asm/mul.asm
> +                mov             r9, rcx
Сделай нормально через ```lea```

На самом деле вроде как принято ```rsp``` все же менять через ```sub``` + ```add```, но да пофиг

2020-06-29 01:28 UTC, kt-cpp commented on asm/mul.asm
> +;    rdi changed to multiplication position(rdi == rsi + rcx * 8)
Давай просто выделим регистр под это

Т.е. в контракте напишешь, что нужно передать регистр, который указывает на достаточную память, чтобы туда результат записать. Код нужно исправить соответственно

2020-06-29 01:28 UTC, kt-cpp requested changes
Еще чуть-чуть

2020-06-29 11:17 UTC, klinachev commented on asm/mul.asm
> +                mov             r9, rcx
Сделал

2020-06-29 11:20 UTC, klinachev commented on asm/mul.asm
> +;    rdi changed to multiplication position(rdi == rsi + rcx * 8)
Изменил

2020-06-29 23:06 UTC, closed without merging

2020-06-29 23:28 UTC, klinachev commented
Я все сломал, вот новый PR: https://github.com/klinachev/first-term/pull/5